/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Client.Client;
import Client.UpdateTable;
import Commands.JoinCommand;
import GameStates.IGameState;
import java.util.ArrayList;
import mypoker.Card;
import mypoker.Deck;
import mypoker.HandChecker;
import mypoker.Player;
import mypoker.Table;
import mypoker.TableDrawer;

/**
 *
 * @author DannySuarez
 */
public class PokerWindow extends javax.swing.JFrame {

    public static int numPlayers = 4;
    public static int currentPlayer = 0;
    public static int betAmount = 0;
    public static Table table1;
    public static int phase = 0;  //the phase represents what part of the hand we are in 0 = preflop, 1=flop,2=turn,3=river
    public ArrayList<javax.swing.JLabel> playerCardLabels = new ArrayList<>();
    public ArrayList<javax.swing.JLabel> tableCardLabels = new ArrayList<>();
    //public javax.swing.JLabel[] playerLabels;
    public ArrayList<javax.swing.JLabel> playerLabels = new ArrayList<>();
    public Client c;
    IGameState state;
    /**
     * Creates new form NewJFrame
     */
    public PokerWindow() {
        initComponents();
        this.addLabels();
        UpdateTable.generateImageArray(this);
        c = new Client();
        c.connect();
        
        state = c.sendCommand(new JoinCommand(c.getUserName())); 
        state.updateTable(this);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerTurnLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        betButton = new javax.swing.JButton();
        this.betButton.setEnabled(false);
        raiseButton = new javax.swing.JButton();
        this.raiseButton.setEnabled(false);
        betSlider = new javax.swing.JSlider();
        sliderLbl = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        this.checkButton.setEnabled(false);
        foldButton = new javax.swing.JButton();
        this.foldButton.setEnabled(false);
        callButton = new javax.swing.JButton();
        this.callButton.setEnabled(false);
        jPanel5 = new javax.swing.JPanel();
        P3Card1 = new javax.swing.JLabel();
        P3Card2 = new javax.swing.JLabel();
        p3Lbl = new javax.swing.JLabel();
        P3Balance = new javax.swing.JLabel();
        lblP3Name = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        P2Card2 = new javax.swing.JLabel();
        P2Card1 = new javax.swing.JLabel();
        p2Lbl = new javax.swing.JLabel();
        P2Balance = new javax.swing.JLabel();
        lblP2Name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TableCard1 = new javax.swing.JLabel();
        TableCard2 = new javax.swing.JLabel();
        TableCard3 = new javax.swing.JLabel();
        TableCard4 = new javax.swing.JLabel();
        TableCard5 = new javax.swing.JLabel();
        potAmount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        P4Card1 = new javax.swing.JLabel();
        p4Lbl = new javax.swing.JLabel();
        P4Balance = new javax.swing.JLabel();
        P4Card2 = new javax.swing.JLabel();
        lblP4Name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        P1Card1 = new javax.swing.JLabel();
        P1Card2 = new javax.swing.JLabel();
        p1Lbl = new javax.swing.JLabel();
        P1Balance = new javax.swing.JLabel();
        lblP1Name = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("Start Hand");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startHand(evt);
            }
        });

        playerTurnLbl.setText("0");

        betButton.setText("Bet");
        betButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betButtonActionPerformed(evt);
            }
        });

        raiseButton.setText("Raise");
        raiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseActionPerformed(evt);
            }
        });

        betSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderMoved(evt);
            }
        });

        sliderLbl.setText("0");

        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        foldButton.setText("Fold");
        foldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldActionPerformed(evt);
            }
        });

        callButton.setText("Call");
        callButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(betButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(betSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sliderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(foldButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addComponent(callButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betButton)
                    .addComponent(raiseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(betSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foldButton))
                    .addComponent(sliderLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(callButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        P3Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        P3Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        p3Lbl.setText("Balance :  $");

        P3Balance.setText("0");

        lblP3Name.setText("EMPTY");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(P3Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P3Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(p3Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P3Balance))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblP3Name)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P3Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3Lbl)
                    .addComponent(P3Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblP3Name))
        );

        P2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        P2Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        p2Lbl.setText("Balance :  $");

        P2Balance.setText("0");

        lblP2Name.setText("EMPTY");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(P2Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P2Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(p2Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P2Balance))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblP2Name)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P2Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2Lbl)
                    .addComponent(P2Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblP2Name)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        TableCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        TableCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        TableCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        TableCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        TableCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        potAmount.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TableCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(potAmount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TableCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(potAmount)
                .addContainerGap())
        );

        P4Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        p4Lbl.setText("Balance :  $");

        P4Balance.setText("0");

        P4Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        lblP4Name.setText("EMPTY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(P4Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P4Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblP4Name)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(p4Lbl)
                                .addGap(18, 18, 18)
                                .addComponent(P4Balance)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P4Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4Lbl)
                    .addComponent(P4Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblP4Name)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        P1Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        P1Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackBackground.jpg"))); // NOI18N

        p1Lbl.setText("Balance :  $");

        P1Balance.setText("0");

        lblP1Name.setText("EMPTY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(P1Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(P1Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblP1Name)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p1Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P1Balance)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Lbl)
                    .addComponent(P1Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblP1Name)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jMenu2.setText("New Game");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(playerTurnLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1)))
                .addGap(92, 92, 92)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(523, 523, 523))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(playerTurnLbl)))
                        .addGap(96, 96, 96)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //if a player bets or raises everyone elses hasBet flag needs to be set back to true so that they may then raise fold or call 
    private void betButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betButtonActionPerformed
        this.betOrRaise();
    }//GEN-LAST:event_betButtonActionPerformed

    

    private void startHand(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startHand
        this.resetTable(); //some of the code in this method is repatative with the start hand code
    }//GEN-LAST:event_startHand

    private void foldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldActionPerformed
        //table1.getPlayers().get(currentPlayer).setTurn(false);
        table1.getPlayers().get(currentPlayer).setHasBet(true);
        table1.getPlayers().get(currentPlayer).setInHand(false);
        table1.decPlayersInHand();

        //if all but one player has folded the round is over
        if (table1.getPlayersInHand() == 1)
        {
            //the hand is over
            payWinner(lastPlayer());
        } else
        {
            checkPhaseChange();
        }

    }//GEN-LAST:event_foldActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        //table1.getPlayers().get(currentPlayer).setTurn(false);
        table1.getPlayers().get(currentPlayer).setHasBet(true);
        checkPhaseChange();
    }//GEN-LAST:event_checkButtonActionPerformed

    private void sliderMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMoved
        this.sliderLbl.setText(String.valueOf(this.betSlider.getValue()));
        //System.out.println("slider moved");
    }//GEN-LAST:event_sliderMoved

    private void raiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseActionPerformed
        this.betOrRaise();
    }//GEN-LAST:event_raiseActionPerformed

    private void callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callActionPerformed
        Player p = table1.getPlayers().get(currentPlayer);
        p.setHasBet(true);
        p.decBalance(betAmount); //COME BACK TO THIS 
        table1.incPot(betAmount);
        this.potAmount.setText(Double.toString(table1.getPot()));
        playerLabels.get(currentPlayer).setText(String.valueOf(p.getBalance()));
        checkPhaseChange();
    }//GEN-LAST:event_callActionPerformed

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        Table t = new Table(numPlayers);
        table1 = t;
    }//GEN-LAST:event_newGameActionPerformed

    private void checkPhaseChange() {
        if (playersStillWaiting())
        { //if there are still players waiting to bet
            currentPlayer = choosePlayer();
        } else
        { //if we get here then move to the next phase
            this.nextPhase();
        }
    }

    private void changePhase() {
        if (phase == 3)
        {
            phase = 0;
        } else
        {
            phase++;
        }

        currentPlayer = 3;
        this.setBetFlags();
        currentPlayer = choosePlayer();
    }

    public void nextPhase() {
        this.betButton.setEnabled(true);
        this.checkButton.setEnabled(true);
        this.foldButton.setEnabled(true);
        this.raiseButton.setEnabled(false);
        this.callButton.setEnabled(false);
        switch (phase)
        {
            case 0:
                TableDrawer.dealFlop(table1, this);
                break;
            case 1:
                TableDrawer.dealTurn(table1, this);
                break;
            case 2:
                TableDrawer.dealRiver(table1, this);
                break;
            case 3:
                checkWinner();
                System.out.println("HAND IS OVER");
                break;
        }
        changePhase();
    }
//Rework this probably also this doesnt consider ties

    public void checkWinner() {
        int currentRank = 100;
        int currentSum = 0;
        int currentWinner = 100;
        ArrayList<Card> cards = new ArrayList<Card>();
        for (Card c : table1.getCards())
        {
            cards.add(c);
        }
        for (int i = 0; i < table1.getPlayers().size(); i++)
        {
            Player p = table1.getPlayers().get(i);
            if (p.isInHand())
            {
                cards.add(p.getHand()[0]);
                cards.add(p.getHand()[1]);
                p.setHandRank(HandChecker.findHand(cards));
                System.out.println("Player " + i + " Rank : " + p.getHandRank().getRank());
                cards.remove(cards.size() - 1);
                cards.remove(cards.size() - 1);
            }
        }

        for (int i = 0; i < table1.getPlayers().size(); i++)
        {
            Player p = table1.getPlayers().get(i);
            if (p.isInHand())
            {
                if (p.getHandRank().getRank() < currentRank)
                {
                    currentRank = p.getHandRank().getRank();
                    currentSum = p.getHandRank().getSum();
                    currentWinner = i;
                }
                if (p.getHandRank().getRank() == currentRank && p.getHandRank().getSum() > currentSum)
                {
                    currentRank = p.getHandRank().getRank();
                    currentSum = p.getHandRank().getSum();
                    currentWinner = i;
                }
            }
        }
        payWinner(currentWinner);
        System.out.println("The winner of the hand is Player " + currentWinner);
    }

    public void payWinner(int winner) {
        this.betButton.setEnabled(false);
        this.checkButton.setEnabled(false);
        this.foldButton.setEnabled(false);
        this.raiseButton.setEnabled(false);
        this.callButton.setEnabled(false);
        this.startButton.setEnabled(true);
        Player p = table1.getPlayers().get(winner);
        p.incBalance(table1.getPot());
        playerLabels.get(winner).setText(String.valueOf(p.getBalance()));
    }

    public void printCards(ArrayList<Card> cards) {
        for (Card c : cards)
        {
            System.out.println(c);
        }
    }

    public void betOrRaise() {
        //table1.getPlayers().get(currentPlayer).setTurn(false);
        Player p = table1.getPlayers().get(currentPlayer);
        p.setHasBet(true);
        int amount = this.betSlider.getValue();
        table1.incPot(amount);
        this.potAmount.setText(Double.toString(table1.getPot()));
        p.decBalance(amount);

        this.betButton.setEnabled(false);
        this.checkButton.setEnabled(false);
        this.callButton.setEnabled(true);
        this.raiseButton.setEnabled(true);
        betAmount = amount;
        resetHasBetFlags(); //since a player just bet this means each player now needs to make another turn
        playerLabels.get(currentPlayer).setText(String.valueOf(p.getBalance()));
        currentPlayer = this.choosePlayer();

    }

    public void setBetFlags() {
        for (Player p : table1.getPlayers())
        {
            if (p.isInHand())
            {
                p.setHasBet(false);
            }
        }
    }

    //checks if players in the hand still need to go
    public boolean playersStillWaiting() {
        for (Player p : table1.getPlayers())
        {
            if (p.isInHand() && p.isHasBet() == false)
            {
                return true; //this means at least one player has not gone
            }
        }
        return false;
    }

    public void resetTable() {
        TableDrawer.resetTable(table1, this);
        this.betSlider.setMinimum(0);
        this.betSlider.setMaximum((int) table1.getPlayers().get(0).getBalance());
        table1.clearCards();
        table1.nextHand();
        table1.dealPlayers();
        TableDrawer.startHand(table1, this);
        

        table1.setDeck(new Deck()); //repopulate a new deck
        table1.setPot(0);
        this.betButton.setEnabled(true);
        this.foldButton.setEnabled(true);
        this.raiseButton.setEnabled(false);
        this.checkButton.setEnabled(true);
        this.callButton.setEnabled(false);
        this.startButton.setEnabled(false);
        this.potAmount.setText("0.00");
        currentPlayer = 0; //just assume the same player starts each hand we will implement blinds and what not later
        phase = 0;

    }

    //we need to consider that if the last player to place their bet
    public int choosePlayer() {
        for (int i = currentPlayer + 1; i < table1.getPlayers().size(); i++)
        {
            if (table1.getPlayers().get(i).isInHand() && table1.getPlayers().get(i).isHasBet() == false)
            {
                this.betSlider.setMaximum((int) table1.getPlayers().get(i).getBalance());
                this.playerTurnLbl.setText(String.valueOf(i));
                return i;
            }
        }
        for (int j = 0; j < currentPlayer; j++)
        {
            if (table1.getPlayers().get(j).isInHand() && table1.getPlayers().get(j).isHasBet() == false)
            {
                this.betSlider.setMaximum((int) table1.getPlayers().get(j).getBalance());
                this.playerTurnLbl.setText(String.valueOf(j));
                return j;
            }
        }

        return -1;
    }

    public void resetHasBetFlags() {
        //table1.getPlayers().get(currentPlayer).setTurn(false);
        table1.getPlayers().get(currentPlayer).setHasBet(true);
        for (int i = currentPlayer + 1; i < table1.getPlayers().size(); i++)
        {
            if (table1.getPlayers().get(i).isInHand())
            {
                table1.getPlayers().get(i).setHasBet(false);
            }
        }
        for (int j = 0; j < currentPlayer; j++)
        {
            if (table1.getPlayers().get(j).isInHand())
            {

                table1.getPlayers().get(j).setHasBet(false);
            }
        }
    }

    //once there is only one player in the hand their is a winner that needs to be chosen
    public int lastPlayer() {
        int playerNumber = -1;
        for (int i = 0; i < table1.getPlayers().size(); i++)
        {
            if (table1.getPlayers().get(i).isInHand())
            {
                playerNumber = i;
                break;
            }
        }
        return playerNumber;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                

            }
        });

    }

    public void addLabels() {
        this.playerCardLabels.add(P1Card1);
        this.playerCardLabels.add(P1Card2);
        this.playerCardLabels.add(P2Card1);
        this.playerCardLabels.add(P2Card2);
        this.playerCardLabels.add(P3Card1);
        this.playerCardLabels.add(P3Card2);
        this.playerCardLabels.add(P4Card1);
        this.playerCardLabels.add(P4Card2);

        this.tableCardLabels.add(TableCard1);
        this.tableCardLabels.add(TableCard2);
        this.tableCardLabels.add(TableCard3);
        this.tableCardLabels.add(TableCard4);
        this.tableCardLabels.add(TableCard5);

        this.playerLabels.add(P1Balance);
        this.playerLabels.add(P2Balance);
        this.playerLabels.add(P3Balance);
        this.playerLabels.add(P4Balance);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel P1Balance;
    public javax.swing.JLabel P1Card1;
    public javax.swing.JLabel P1Card2;
    public javax.swing.JLabel P2Balance;
    public javax.swing.JLabel P2Card1;
    public javax.swing.JLabel P2Card2;
    public javax.swing.JLabel P3Balance;
    public javax.swing.JLabel P3Card1;
    public javax.swing.JLabel P3Card2;
    public javax.swing.JLabel P4Balance;
    public javax.swing.JLabel P4Card1;
    public javax.swing.JLabel P4Card2;
    public javax.swing.JLabel TableCard1;
    public javax.swing.JLabel TableCard2;
    public javax.swing.JLabel TableCard3;
    public javax.swing.JLabel TableCard4;
    public javax.swing.JLabel TableCard5;
    private javax.swing.JButton betButton;
    private javax.swing.JSlider betSlider;
    private javax.swing.JButton callButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton foldButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JLabel lblP1Name;
    public javax.swing.JLabel lblP2Name;
    public javax.swing.JLabel lblP3Name;
    public javax.swing.JLabel lblP4Name;
    private javax.swing.JLabel p1Lbl;
    private javax.swing.JLabel p2Lbl;
    private javax.swing.JLabel p3Lbl;
    private javax.swing.JLabel p4Lbl;
    private javax.swing.JLabel playerTurnLbl;
    public javax.swing.JLabel potAmount;
    private javax.swing.JButton raiseButton;
    private javax.swing.JLabel sliderLbl;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

}
